//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acturis
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimReportField
    {
        public int ClaimReportFieldId { get; set; }
        public Nullable<int> ReportQuestionId { get; set; }
        public string ReportAnswerId { get; set; }
        public Nullable<int> ClaimId { get; set; }
        public bool Loaded { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
    }
}
