//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acturis
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimCauseType
    {
        public string ClaimType { get; set; }
        public int ClaimTypeRef { get; set; }
        public string ClaimCause { get; set; }
        public Nullable<int> ClaimCauseRef { get; set; }
    }
}
