//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acturis
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimAmount
    {
        public int ClaimAmountId { get; set; }
        public Nullable<int> ClaimId { get; set; }
        public Nullable<int> AmountRef { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<System.DateTime> AmountDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AmountReceivedFromInsurer { get; set; }
        public string AmountPayee { get; set; }
        public Nullable<decimal> AmountExcessDeducted { get; set; }
        public string ClaimAmountComment { get; set; }
        public Nullable<int> CostHeadingId { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime DateAdded { get; set; }
        public bool Loaded { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
    }
}
