//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acturis
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimHandler
    {
        public int AccountHandlerId { get; set; }
        public string AccountHandler { get; set; }
        public int OfficeId { get; set; }
        public string Office { get; set; }
    }
}
