//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acturis
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimQueue
    {
        public long QueueId { get; set; }
        public string ClaimNo { get; set; }
        public Nullable<int> StatusId { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public int ErrorCount { get; set; }
        public string ErrorType { get; set; }
        public Nullable<int> ClaimId { get; set; }
        public Nullable<int> ClaimRef { get; set; }
        public string AddedBy { get; set; }
        public string ModifiedBy { get; set; }
    }
}
