//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acturis
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimPayment
    {
        public int ClaimPaymentId { get; set; }
        public int ClaimPaymentDetailId { get; set; }
        public int ClaimDetailId { get; set; }
        public Nullable<int> ClaimRef { get; set; }
        public Nullable<int> PolicyVersionRef { get; set; }
        public Nullable<int> CostHeadingId { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<decimal> RecoveredAmount { get; set; }
        public Nullable<decimal> ReservedAmount { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
