//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acturis
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataLoad
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Data { get; set; }
        public string DateAdded { get; set; }
        public bool Loaded { get; set; }
        public int ParentId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public bool Locked { get; set; }
        public string CurrentUser { get; set; }
        public string LastProcessed { get; set; }
        public bool Queued { get; set; }
        public bool EnforceRequired { get; set; }
    }
}
