//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acturis
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClaimMovement
    {
        public int ClaimMovementId { get; set; }
        public Nullable<int> ClaimId { get; set; }
        public Nullable<System.DateTime> AdviceSentDate { get; set; }
        public Nullable<System.DateTime> AdviceReceivedDate { get; set; }
        public Nullable<System.DateTime> MovementDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ProcessCompleteDate { get; set; }
        public string ClaimMovementStatus { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public string CancelledReason { get; set; }
        public string CancelledNarrative { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    }
}
