//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acturis
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClaim
    {
        public int ClaimId { get; set; }
        public Nullable<int> PolicySectionId { get; set; }
        public string ClaimStatus { get; set; }
        public string ClaimReference { get; set; }
        public Nullable<int> LossRegisterId { get; set; }
        public Nullable<decimal> SumInsured { get; set; }
        public string SumInsuredCurrencyISO { get; set; }
        public string LossName { get; set; }
        public Nullable<System.DateTime> LossDateFrom { get; set; }
        public Nullable<System.DateTime> LossDateTo { get; set; }
        public string LossLocation { get; set; }
        public string ClaimDescription { get; set; }
        public string VesselAircraftConvey { get; set; }
        public string Claimant { get; set; }
        public string ContentiousLossIndicator { get; set; }
        public Nullable<bool> Backloaded { get; set; }
        public string BackloadedDescription { get; set; }
        public string UniqueClaimReference { get; set; }
        public string Interest { get; set; }
        public Nullable<int> InsuredId { get; set; }
        public string InsuredName { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string ClientName { get; set; }
        public Nullable<int> ReinsuredId { get; set; }
        public string ReinsuredName { get; set; }
        public Nullable<int> PrimaryClaimHandlerId { get; set; }
        public string PrimaryClaimHandlerName { get; set; }
        public Nullable<int> PrimaryClaimHandlerTeamId { get; set; }
        public string PrimaryClaimHandlerTeamName { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    }
}
