//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acturis
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClaimMovementBreakdown
    {
        public int ClaimMovementBreakdownId { get; set; }
        public Nullable<int> ClaimMovementId { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string ClaimType { get; set; }
        public string AccountHolderReference { get; set; }
        public string DebitCreditIndicator { get; set; }
        public string OriginalCurrencyISO { get; set; }
        public string SettlementCurrencyISO { get; set; }
        public Nullable<decimal> HundredPercentOriginalAmount { get; set; }
        public Nullable<decimal> HundredPercentSettlementAmount { get; set; }
        public Nullable<decimal> OrderOriginalAmount { get; set; }
        public Nullable<decimal> OrderSettlementAmount { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    }
}
