//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acturis
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPolicySection
    {
        public int PolicySectionId { get; set; }
        public Nullable<int> PolicyId { get; set; }
        public string PolicySectionCode { get; set; }
        public string PolicySectionDescription { get; set; }
        public Nullable<bool> MasterBinder { get; set; }
        public Nullable<bool> Facility { get; set; }
        public Nullable<int> FacilityParent { get; set; }
        public string PolicySectionStatus { get; set; }
        public string Product { get; set; }
        public Nullable<int> ProductClassId { get; set; }
        public string ProductClass { get; set; }
        public Nullable<decimal> OrderPercent { get; set; }
        public Nullable<int> OfWhole { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    }
}
