//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelsLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        public Claim()
        {
            this.ClaimFieldGroups = new HashSet<ClaimFieldGroup>();
        }
    
        public int ClaimID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ClaimTemplateID { get; set; }
        public Nullable<int> ClaimStatusID { get; set; }
        public Nullable<int> WillisEmployeeID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ClaimStatu ClaimStatu { get; set; }
        public virtual ClaimTemplate ClaimTemplate { get; set; }
        public virtual Country Country { get; set; }
        public virtual WillisEmployee WillisEmployee { get; set; }
        public virtual ICollection<ClaimFieldGroup> ClaimFieldGroups { get; set; }
        public virtual User User { get; set; }
    }
}
