//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelsLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimFieldTemplate
    {
        public ClaimFieldTemplate()
        {
            this.ClaimFields = new HashSet<ClaimField>();
            this.ReportFields = new HashSet<ReportField>();
        }
    
        public int ClaimFieldTemplateID { get; set; }
        public int ClaimFieldGroupTemplateID { get; set; }
        public Nullable<int> FieldTypeID { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public bool Saved { get; set; }
        public bool Mandatory { get; set; }
        public Nullable<int> FieldOrder { get; set; }
        public string ShortTextDefaultValue { get; set; }
        public string LongTextDefaultValue { get; set; }
        public Nullable<System.DateTime> DateTimeDefaultValue { get; set; }
        public Nullable<decimal> CurrecncyDefaultValue { get; set; }
        public byte[] FileDefaultValue { get; set; }
        public string CountryDefaultValue { get; set; }
        public string DropDownDefaultValue { get; set; }
        public string MultiChoiceDefaultValue { get; set; }
        public Nullable<System.DateTime> DateDefaultValue { get; set; }
        public Nullable<int> IntegerDefaultValue { get; set; }
        public Nullable<double> FloatDefaultValue { get; set; }
        public Nullable<double> RangeDefaultValue { get; set; }
        public string DropDownLevel2Default { get; set; }
    
        public virtual ICollection<ClaimField> ClaimFields { get; set; }
        public virtual ClaimFieldGroupTemplate ClaimFieldGroupTemplate { get; set; }
        public virtual Country Country { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual FieldType FieldType { get; set; }
        public virtual ICollection<ReportField> ReportFields { get; set; }
    }
}
