//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelsLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimFieldGroupTemplate
    {
        public ClaimFieldGroupTemplate()
        {
            this.ClaimFieldTemplates = new HashSet<ClaimFieldTemplate>();
        }
    
        public int ClaimFieldGroupTemplateID { get; set; }
        public Nullable<int> ClaimTemplateID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ItemOrder { get; set; }
    
        public virtual ClaimTemplate ClaimTemplate { get; set; }
        public virtual ICollection<ClaimFieldTemplate> ClaimFieldTemplates { get; set; }
    }
}
