//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelsLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimField
    {
        public int ClaimFieldID { get; set; }
        public Nullable<int> ClaimFieldGroupID { get; set; }
        public Nullable<int> ClaimFieldTemplateID { get; set; }
        public string ShortTextValue { get; set; }
        public string LongTextValue { get; set; }
        public Nullable<System.DateTime> DateTimeValue { get; set; }
        public Nullable<decimal> CurrecncyValue { get; set; }
        public byte[] FileValue { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string CountryValue { get; set; }
        public string DropDownValue { get; set; }
        public string MultiChoiceValue { get; set; }
        public Nullable<System.DateTime> DateValue { get; set; }
        public Nullable<int> IntegerValue { get; set; }
        public Nullable<double> FloatValue { get; set; }
        public Nullable<double> RangeValue { get; set; }
        public string DropDownLevel2Value { get; set; }
    
        public virtual ClaimFieldGroup ClaimFieldGroup { get; set; }
        public virtual ClaimFieldTemplate ClaimFieldTemplate { get; set; }
    }
}
