//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelsLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimFieldGroup
    {
        public ClaimFieldGroup()
        {
            this.ClaimFields = new HashSet<ClaimField>();
        }
    
        public int ClaimFieldGroupID { get; set; }
        public Nullable<int> ClaimID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ItemOrder { get; set; }
    
        public virtual ICollection<ClaimField> ClaimFields { get; set; }
        public virtual Claim Claim { get; set; }
    }
}
