//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelsLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimTemplate
    {
        public ClaimTemplate()
        {
            this.ClaimFieldGroupTemplates = new HashSet<ClaimFieldGroupTemplate>();
            this.Clients = new HashSet<Client>();
            this.Claims = new HashSet<Claim>();
            this.ReportTemplates = new HashSet<ReportTemplate>();
        }
    
        public int ClaimTemplateID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public string DisplayMode { get; set; }
    
        public virtual ICollection<ClaimFieldGroupTemplate> ClaimFieldGroupTemplates { get; set; }
        public virtual ICollection<Client> Clients { get; set; }
        public virtual ICollection<Claim> Claims { get; set; }
        public virtual ICollection<ReportTemplate> ReportTemplates { get; set; }
    }
}
