//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelsLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageElement
    {
        public int PageElementID { get; set; }
        public Nullable<int> PageSetupID { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> ElementTop { get; set; }
        public Nullable<double> ElementLeft { get; set; }
        public Nullable<int> ReportID { get; set; }
        public string FrameID { get; set; }
        public string Title { get; set; }
    
        public virtual PageSetup PageSetup { get; set; }
        public virtual ReportTemplate ReportTemplate { get; set; }
    }
}
