//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelsLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportTemplate
    {
        public ReportTemplate()
        {
            this.ReportFields = new HashSet<ReportField>();
            this.PageElements = new HashSet<PageElement>();
        }
    
        public int ReportID { get; set; }
        public string Name { get; set; }
        public string ReportType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string OrderDirection { get; set; }
        public Nullable<int> NumberofRecords { get; set; }
        public string Options { get; set; }
        public Nullable<int> ClaimTemplateId { get; set; }
        public string Colour1 { get; set; }
        public string Colour2 { get; set; }
        public string Colour3 { get; set; }
        public string Colour4 { get; set; }
        public string Colour5 { get; set; }
        public string HAxis { get; set; }
        public string HAxisColour { get; set; }
        public string VAxis { get; set; }
        public string VAxisColour { get; set; }
        public string ZAxis { get; set; }
        public string ZAxisColour { get; set; }
        public string FontFamily { get; set; }
        public Nullable<double> FontSize { get; set; }
        public string NameColour { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ReportField> ReportFields { get; set; }
        public virtual ICollection<PageElement> PageElements { get; set; }
        public virtual ClaimTemplate ClaimTemplate { get; set; }
    }
}
