//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelsLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Claims = new HashSet<Claim>();
            this.PageSetups = new HashSet<PageSetup>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string DisplayName { get; set; }
        public string Email { get; set; }
        public string RegistrationClientName { get; set; }
        public bool Activated { get; set; }
        public Nullable<int> ClientID { get; set; }
    
        public virtual ICollection<Claim> Claims { get; set; }
        public virtual ICollection<PageSetup> PageSetups { get; set; }
    }
}
