//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelsLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WillisEmployee
    {
        public WillisEmployee()
        {
            this.Claims = new HashSet<Claim>();
        }
    
        public int WillisEmployeeID { get; set; }
        public string EmployeeUserID { get; set; }
        public string DisplayName { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Claim> Claims { get; set; }
    }
}
